# Generated by Django 5.2.8 on 2025-11-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video Lesson'), ('story', 'Story Book'), ('game', 'Interactive Game')], max_length=20)),
                ('age_group', models.CharField(choices=[('3-5', '3-5 years'), ('6-8', '6-8 years'), ('9-12', '9-12 years')], max_length=10)),
                ('media_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
