# Generated by Django 5.2.8 on 2025-11-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='views',
        ),
    ]
